# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div.xci
# IP: The module: 'clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div.xci
# IP: The module: 'clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: f:/FPGA/turorial_ms/clock_IP/clock_IP.srcs/sources_1/ip/clk_div/clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
