# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FPGA/turorial_ms/fifo/fifo.cache/wt [current_project]
set_property parent.project_path F:/FPGA/turorial_ms/fifo/fifo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
read_ip -quiet f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test.xci
set_property is_locked true [get_files f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fifo_test -part xc7a35ticsg324-1L -mode out_of_context

rename_ref -prefix_all fifo_test_

write_checkpoint -force -noxdef fifo_test.dcp

catch { report_utilization -file fifo_test_utilization_synth.rpt -pb fifo_test_utilization_synth.pb }

if { [catch {
  file copy -force F:/FPGA/turorial_ms/fifo/fifo.runs/fifo_test_synth_1/fifo_test.dcp f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir F:/FPGA/turorial_ms/fifo/fifo.ip_user_files/ip/fifo_test]} {
  catch { 
    file copy -force f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test_stub.v F:/FPGA/turorial_ms/fifo/fifo.ip_user_files/ip/fifo_test
  }
}

if {[file isdir F:/FPGA/turorial_ms/fifo/fifo.ip_user_files/ip/fifo_test]} {
  catch { 
    file copy -force f:/FPGA/turorial_ms/fifo/fifo.srcs/sources_1/ip/fifo_test/fifo_test_stub.vhdl F:/FPGA/turorial_ms/fifo/fifo.ip_user_files/ip/fifo_test
  }
}
